### GENERAL SETTINGS ###

# Site settings
title: OSSSanitizer
email: osssanitizer@gmail.com
description: "OSSSanitizer is a suite of web services for automating open-source software risk management."

#Google analytics code in the format XX-nnnnnnnn-n
analytics: UA-109487891-1
baseurl: "" #important: start with /
url: http://osssanitizer.github.io

# Google Analytics
google_analytics: UA-109487891-1

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: osssanitizer

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  #primary: "#00b3fe" #"#F70031"
  #primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Footer settings
footer:
  copyright: OSSSanitizer

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: slack
    url: https://osssanitizer.slack.com
  - title: github
    url: https://github.com/osssanitizer
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Atlanta, GA
    - United States.
email: osssanitizer AT gmail DOT com
tel: +1 OSS SANITZE

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Ashish Bijlani
    position: Co-founder
    text: Ashish is a PhD student at Georgia Institute of Technology. He has over 10 years of industry experience in system software development.
    img: ashish.jpg
    social:
      - title: linkedin #use for email address
        url: https://sites.google.com/site/ashishbijlani/
      - title: google
        url: https://scholar.google.com/citations?user=h07HQ50AAAAJ&hl=en
  - name: Ruian Duan
    position: Co-founder
    text: Ruian is a PhD student at Georgia Institute of Technology. eceived B.E. degree from Department of Compute Science and Technology, Tsinghua University.
    img: ruian.jpg
    social:
      - title: linkedin #use for email address
        url: https://www.cc.gatech.edu/~rduan9

# Clients information. Shown on Home and About pages.
clients:
  - name: Artifex Inc. # https://www.artifex.com
    img: artifex.png
  - name: FFMpeg 
    img: ffmpeg.png
#  - name: VideoLAN
#    img: videolan.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Automate Open Source Software Risk Management with OSSSanitizer"

# Testimonial content. Shown on Home and About page.
testimonial:
    message1: "Thank you so much for your diligence.  We usually get reports of AGPL violators about 15 times per year.  It is an extraordinary day when we receive 9,824!!!"
    author1: Miles Jones
    position1: President, Artifex Software Inc.

    message2: "We continue to contact license violators identified by your work.  Many have agreed to remove MuPDF, a few have agreed to become commercial customers."
    author2: Henry Stiles
    position2: VP of Engineering, Artifex Software Inc.
