# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://221prospect.com
title: 221 Prospect
email: info@221prospect.com
author: Alan McConchie
description: > # "Write an awesome description for your new site here. 
  Coming soon at 221 Prospect: meeting space, event rental, coworking for designers and creatives. In the heart of the Downtown Bellingham Arts District
copyright: 'Copyright &copy; 2016 Alan McConchie. All Rights Reserved.'
credits: '221 Prospect Street, Bellingham, WA 98225'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
#    url: https://twitter.com/221prospect
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: email
#    url: mailto:info@221prospect.com
