# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://osssanitizer.github.io
title: OSSSanitizer
email: osssanitizer@gmail.com
author: OSSSanitizer
description: > # "Write an awesome description for your new site here. 
   OSSSanitizer is a suite of webservices to manage security and legal risks introduced by OSS components in your apps.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
#    url: https://osssanitizer.github.io
#  - title: github
#    url: https://osssanitizer.github.io
#  - title: email
#    url: mailto:info@221prospect.com
